# Generated by Django 2.0.4 on 2018-04-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamgenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='person_count',
        ),
    ]
