# Generated by Django 2.0.4 on 2018-04-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamgenerator', '0002_remove_team_person_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='person_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
